ALTER TABLE users
ADD COLUMN email VARCHAR NOT NULL,
ADD COLUMN first_name VARCHAR NOT NULL,
ADD COLUMN last_name VARCHAR NOT NULL,
ADD COLUMN birthday VARCHAR NOT NULL,
ADD COLUMN password VARCHAR NOT NULL;
